#!/bin/sh

# Evaluate OS (Linux, MacOS)
system_type=$(uname -s)

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "💿 Initializing submodules…"
yadm submodule update --recursive --init

# Install Homebrew on MacOS and, if available, a bundle of recipes
if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "💿 Installing homebrew…"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.brewfile" ]; then
    echo "💿 Updating homebrew bundle…"
    brew bundle --global
  fi

fi
